apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.pod }}
  labels:
    k8s-app: {{ .Values.pod }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Values.pod }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.pod }}
        name: {{ .Values.pod }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.pod }}
        imagePullPolicy: Always
        env: 
        - name: K8S_API
          value: {{ .Values.K8S_API }}
        - name: TEAM
          value: {{ .Values.TEAM }}
        - name: LOGIN
          value: {{ .Values.LOGIN }}
        - name: PASSWORD
          value: {{ .Values.PASSWORD }}
        - name: SERVER
          value: {{ .Values.SERVER }}
        - name: CHANNEL
          value: {{ .Values.CHANNEL }}
